# Generated by Django 3.1.6 on 2021-03-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'Programming'), (2, 'Hardware'), (3, 'Networking')], default=0),
        ),
    ]
