# Generated by Django 3.1.6 on 2021-03-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210308_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(0, 'General'), (1, 'Programming'), (2, 'Hardware'), (3, 'Networking')], default=0, max_length=20),
        ),
    ]
