# Generated by Django 3.1.6 on 2021-03-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210310_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, default='NO DESCRIPTION AVAILABLE', max_length=200, null=True),
        ),
    ]
