# Generated by Django 3.1.6 on 2021-03-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210310_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='NO DESCRIPTION AVAILABLE', max_length=200),
        ),
    ]
